require "open-uri"
require "nokogiri"
require "./lib/dems2020/debatescraper"
\require "./lib/dems2020/candidatescraper"
require "./lib/dems2020/wikipediascraper"
require "./lib/dems2020/realclearpoliticsscraper"
require "pry"
